spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    name: ownDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1/test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      initial-size: 1
      max-active: 20
  #应用配置
  application:
    name: test

  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  mapper-locations: classpath:com.july.mybatis.mapper/*.xml
  type-aliases-package: com.july.mybatis.entity
  type-enums-package: com.july.mybatis.entity.enums
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


server:
  port: 8702
  servlet:
     context-path: /test

